### ISSUE TITLE
problemas nas images

### ISSUE THREAD

**Issue by HugoMarquesIPT** [iptomar/PSI-Grupo-A-2019-2020#10]
o comando getImage não funciona apesar das nossas tentativas

**Comment by LuisTorresIPT** [comment]
Apesar de tentarmos com varias opções o comando fica preso sem retorno válido.
o body que utilizamos é:
{
"data":{"id":1}
}
Tentámos usando GET e POST.

**Comment by Difficulty01** [comment]
foi manualmente criado um ficheiro chamado 1.txt pelo que o getimage funciona

o body correto é:
{
	"data":"1"
}

actualmente eu estou a planear em algum tempo fazer a estandardização de todos os pedidos á api
