### ISSUE TITLE
Variaveis que aceitam valores improprios

### ISSUE THREAD

**Issue by LuisTorresIPT** [iptomar/PSI-Grupo-A-2019-2020#11]
No Register user os campos do email e da idade aceitam valores string além de números.

![image](https://user-images.githubusercontent.com/61334427/82687215-ed400780-9c4e-11ea-933e-18e8d09eb2a3.png)

**Comment by Difficulty01** [comment]
o e-mail irá ser actualizado para apenas receber um e-mail válido
a idade não deveria de funcionar(serão necessários mais testes do nosso lado(na bd é um integer))

**Comment by Difficulty01** [comment]
a idade é tratada como uma string apesar de ser um integer pelo knex

ao que parece têm algo a ver com javascript

**Comment by Difficulty01** [comment]
a idade foi validada

não consigo testar agora quando acabar os testes fecho este issue

**Comment by Difficulty01** [comment]
testado e resolvido
