### ISSUE TITLE
Erros no GiveAdmin

### ISSUE THREAD

**Issue by LuisTorresIPT** [iptomar/PSI-Grupo-A-2019-2020#14]
O giveAdmin permite dar direitos a e-mails inexistentes ou errados. Não testa se o e-mail está certo.

**Comment by HugoMarquesIPT** [comment]
O mesmo aplica-se ao removeAdmin

**Comment by Difficulty01** [comment]
ele não dá direitos nem tira

só se o e-mail estiver certo

vou fazer outra mensagem caso nenhum seja alterado

**Comment by Difficulty01** [comment]
agora se não alterar nenhum retorna uma mensagem de aviso
