### ISSUE TITLE
Associar pontos a roteiro

### ISSUE THREAD

**Issue by joaoxpedrox** [iptomar/PSI-Grupo-A-2019-2020#18]
![image](https://user-images.githubusercontent.com/48485535/83453977-572c8e00-a453-11ea-9c40-c62a63dd320f.png)
![image](https://user-images.githubusercontent.com/48485535/83453997-5d226f00-a453-11ea-8120-abf6595ed919.png)
Erro ao associar ponto a roteiro. Loggado como Admin.

**Comment by LuisTorresIPT** [comment]
No readme do backend_v3 tanto o pointtoroute e pointoutroute estão pouco explicitos o que retornam.

**Comment by Difficulty01** [comment]
o erro que está aí nessa screenshot significa que ele está a tentar enviar 2 respostas ao mesmo pedido

completamente normal

porque o backend está assíncrono e por isso continua mesmo chegando a clausula catch do insert

**Comment by Difficulty01** [comment]
se isto só ocorrer ao associar o problema vai ser resolvido no próximo commit

caso o remover também tiver problemas reabre o problema
